usage:
  mandatory-flags:
    desc: In order to take advantage of GPU acceleration, Singularity must be made aware of Nvidia
    flags: "--singularity-args='--nv'"
  software-stack-deployment:
    conda: true
    singularity: true
    singularity+conda: true
  report: true
